# Generated by Django 3.1.7 on 2021-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210220_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microsoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tesla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Amazon',
        ),
    ]
