# Generated by Django 3.1.7 on 2021-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210220_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='name',
            field=models.CharField(default='amazon', max_length=120),
        ),
        migrations.AddField(
            model_name='google',
            name='name',
            field=models.CharField(default='google', max_length=120),
        ),
    ]
