# Generated by Django 3.1.7 on 2021-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210224_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoft',
            name='name',
            field=models.CharField(default='microsoft', max_length=120),
        ),
        migrations.AddField(
            model_name='tesla',
            name='name',
            field=models.CharField(default='tesla', max_length=120),
        ),
    ]
