# Generated by Django 3.1.7 on 2021-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210224_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
