# Generated by Django 3.1.7 on 2021-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='para1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='amazon',
            name='para2',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='amazon',
            name='para3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
