# Generated by Django 3.1.7 on 2021-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20210228_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='para1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='trending',
            name='para2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='trending',
            name='para3',
            field=models.CharField(default='', max_length=250),
        ),
    ]
