# Generated by Django 3.1.7 on 2021-03-01 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20210301_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Day'),
        ),
    ]
