# Generated by Django 3.1.7 on 2021-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_trending_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='semester',
        ),
        migrations.AddField(
            model_name='trending',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
    ]
