# Generated by Django 3.1.7 on 2021-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_auto_20210301_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPLICANT_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCHEDULED_AT', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
