# Generated by Django 3.1.7 on 2021-03-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_applicant_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPLICANT_DATA',
        ),
    ]
