# Generated by Django 3.1.7 on 2021-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_trending_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='now',
        ),
        migrations.AddField(
            model_name='google',
            name='para1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='google',
            name='para2',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='google',
            name='para3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='google',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para2',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para2',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tesla',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='google',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='google',
            name='name',
            field=models.CharField(default='amazon', max_length=120),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
