# Generated by Django 3.1.7 on 2021-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_auto_20210302_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
