# Generated by Django 3.1.7 on 2021-03-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_trending_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon',
            name='date',
        ),
        migrations.RemoveField(
            model_name='google',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='microsoft',
            name='date',
        ),
        migrations.RemoveField(
            model_name='new',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tesla',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='date',
        ),
    ]
