# Generated by Django 3.1.7 on 2021-03-07 14:05

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_auto_20210307_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='dateint',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='trending',
            name='month',
            field=models.DateField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), (
                'August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
    ]
