# Generated by Django 3.1.7 on 2021-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_auto_20210307_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='date',
            new_name='dateint',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='dt',
        ),
        migrations.AlterField(
            model_name='trending',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
    ]
