# Generated by Django 3.1.7 on 2021-03-07 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_auto_20210307_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
