# Generated by Django 3.1.7 on 2021-03-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_trending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 7, 23, 8, 34, 438268)),
        ),
    ]
