# Generated by Django 3.1.7 on 2021-03-07 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_trending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='now',
            field=models.CharField(default=datetime.datetime(2021, 3, 7, 18, 3, 2, 933561, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='trending',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 7, 23, 33, 2, 933561)),
        ),
    ]
