# Generated by Django 3.1.7 on 2021-03-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_auto_20210307_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='now',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='time',
        ),
    ]
