# Generated by Django 3.1.7 on 2021-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_auto_20210307_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='now',
            field=models.CharField(default='23:45:21', max_length=20),
        ),
    ]
