# Generated by Django 3.1.7 on 2021-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_trending_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.CharField(default=(2021, 3, 7, 23, 46, 27, 6, 66, 0), max_length=20),
        ),
    ]
