# Generated by Django 3.1.7 on 2021-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0034_auto_20210307_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:25:29'),
        ),
    ]
