# Generated by Django 3.1.7 on 2021-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0038_auto_20210312_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cybersecurity', max_length=120)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=5000)),
                ('para1', models.CharField(default='', max_length=200)),
                ('para2', models.CharField(default='', max_length=800)),
                ('para3', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='facebook', max_length=120)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=5000)),
                ('para1', models.CharField(default='', max_length=200)),
                ('para2', models.CharField(default='', max_length=800)),
                ('para3', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='privacy', max_length=120)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=5000)),
                ('para1', models.CharField(default='', max_length=200)),
                ('para2', models.CharField(default='', max_length=800)),
                ('para3', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:58:18'),
        ),
    ]
