# Generated by Django 3.1.7 on 2021-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0041_auto_20210313_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='18:09:41'),
        ),
    ]
