# Generated by Django 3.1.7 on 2021-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0057_auto_20210316_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='subtitle',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='00:38:29'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para2',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
