# Generated by Django 3.1.7 on 2021-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0058_auto_20210317_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='videosrc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tesla',
            name='videosrc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:11:16'),
        ),
    ]
