# Generated by Django 3.1.7 on 2021-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0059_auto_20210317_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='videosrc',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='videosrc',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:29:25'),
        ),
    ]
