# Generated by Django 3.1.7 on 2021-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0061_auto_20210317_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/videoblocks-editorial-tesla-logo-on-glass-building_rshyodisg__f77313a2da3c7b634f08a3353bcae9aa__P360.mp4', max_length=500),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:37:23'),
        ),
    ]
