# Generated by Django 3.1.7 on 2021-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0062_auto_20210317_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='videosrc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:37:48'),
        ),
    ]
