# Generated by Django 3.1.7 on 2021-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0063_auto_20210317_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='videosrc',
            field=models.CharField(default='https://cdn.videvo.net/videvo_files/video/free/2020-05/small_watermarked/200422%20_Digital%20Media%20Icons_02_4k_010_preview.webm', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='22:53:16'),
        ),
    ]
