# Generated by Django 3.1.7 on 2021-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0064_auto_20210317_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoft',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/editorial-microsoft-logo-on-glass-building_smh9jzx5x__ff386595dcb6e950e47f643dfb7e6f64__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='23:08:46'),
        ),
    ]
