# Generated by Django 3.1.7 on 2021-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0065_auto_20210317_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/videoblocks-editorial-amazon-logo-on-glass-building_hwejn98w_b__e76572479d6e0eef1ed47aedc20ca538__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='00:12:21'),
        ),
    ]
