# Generated by Django 3.1.7 on 2021-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0066_auto_20210318_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='cybersecurity',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='energy',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='environment',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='facebook',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='films',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='gaming',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='headphones',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='health',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='instagram',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='laptops',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='nasa',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='netflix',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='phones',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='privacy',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='spacex',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='speakers',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='sports',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='television',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='twitter',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='youtube',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='apple',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/S7LdoaUwiqo7rqib/videoblocks-creative-data-security-concept-with-lock_hglivjo0s__46d32b5b62d783b6322917d5a40ff2c1__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='00:17:59'),
        ),
    ]
