# Generated by Django 3.1.7 on 2021-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0067_auto_20210318_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='trending',
            name='para4',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='trending',
            name='para5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trending',
            name='para6',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='trending',
            name='para7',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trending',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/videoblocks-editorial-amazon-logo-on-glass-building_hwejn98w_b__e76572479d6e0eef1ed47aedc20ca538__P360.mp4', max_length=300),
        ),
        migrations.AddField(
            model_name='trending',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='20:38:25'),
        ),
    ]
