# Generated by Django 3.1.7 on 2021-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0068_auto_20210318_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='20:39:24'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='youtubevideo',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
