# Generated by Django 3.1.7 on 2021-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0069_auto_20210318_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='21:06:50'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para1',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para3',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para5',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='trending',
            name='para7',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
