# Generated by Django 3.1.7 on 2021-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0070_auto_20210318_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='21:08:18'),
        ),
    ]
