# Generated by Django 3.1.7 on 2021-03-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0072_auto_20210320_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot',
            name='now',
            field=models.TimeField(default='00:36:07'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='new',
            name='now',
            field=models.TimeField(default='00:36:07'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='00:36:07'),
        ),
    ]
