# Generated by Django 3.1.7 on 2021-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0073_auto_20210320_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot',
            name='description',
        ),
        migrations.AlterField(
            model_name='hot',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AlterField(
            model_name='hot',
            name='now',
            field=models.TimeField(default='00:58:13'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='youtubevideo',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='new',
            name='now',
            field=models.TimeField(default='00:58:13'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='00:58:13'),
        ),
    ]
