# Generated by Django 3.1.7 on 2021-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0074_auto_20210320_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='hot',
            name='now',
            field=models.TimeField(default='01:20:31'),
        ),
        migrations.AlterField(
            model_name='new',
            name='now',
            field=models.TimeField(default='01:20:31'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='01:20:31'),
        ),
    ]
