# Generated by Django 3.1.7 on 2021-03-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0075_auto_20210320_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='hot',
            name='now',
            field=models.TimeField(default='01:21:14'),
        ),
        migrations.AlterField(
            model_name='new',
            name='now',
            field=models.TimeField(default='01:21:14'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='01:21:14'),
        ),
    ]
