# Generated by Django 3.1.7 on 2021-03-20 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0078_auto_20210320_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='description',
        ),
        migrations.RemoveField(
            model_name='microsoft',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tesla',
            name='description',
        ),
        migrations.AddField(
            model_name='google',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='google',
            name='dateint',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='google',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='google',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='google',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='google',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AddField(
            model_name='google',
            name='para4',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='google',
            name='para5',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='google',
            name='para6',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='google',
            name='para7',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='google',
            name='subtitle',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='google',
            name='youtubevideo',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='dateint',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para4',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para5',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para6',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='para7',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='subtitle',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='youtubevideo',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='tesla',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tesla',
            name='dateint',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='tesla',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='tesla',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tesla',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='tesla',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para4',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para5',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para6',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='tesla',
            name='para7',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='tesla',
            name='subtitle',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tesla',
            name='youtubevideo',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AlterField(
            model_name='google',
            name='name',
            field=models.CharField(default='google', max_length=120),
        ),
        migrations.AlterField(
            model_name='google',
            name='para1',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='google',
            name='para2',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='google',
            name='para3',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='google',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/videoblocks-editorial-amazon-logo-on-glass-building_hwejn98w_b__e76572479d6e0eef1ed47aedc20ca538__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='hot',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AlterField(
            model_name='hot',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='para1',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='para2',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='para3',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/videoblocks-editorial-amazon-logo-on-glass-building_hwejn98w_b__e76572479d6e0eef1ed47aedc20ca538__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='new',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AlterField(
            model_name='new',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='para1',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='para2',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='para3',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='videosrc',
            field=models.CharField(default='https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/UD7CEz6/videoblocks-editorial-amazon-logo-on-glass-building_hwejn98w_b__e76572479d6e0eef1ed47aedc20ca538__P360.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='11:20:50'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
    ]
