# Generated by Django 3.1.7 on 2021-03-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0079_auto_20210320_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
        migrations.AlterField(
            model_name='google',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
        migrations.AlterField(
            model_name='google',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hot',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='new',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
        migrations.AlterField(
            model_name='tesla',
            name='youtubevideo',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='trending',
            name='now',
            field=models.TimeField(default='11:23:32'),
        ),
    ]
